version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=rest_api_project
      - POSTGRES_USER=rest_api_project
      - POSTGRES_PASSWORD=123456789
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db